# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(367, 494)
        self.label1 = QtWidgets.QLabel(Dialog)
        self.label1.setGeometry(QtCore.QRect(10, 20, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 210, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.flowOutLbl = QtWidgets.QLabel(Dialog)
        self.flowOutLbl.setGeometry(QtCore.QRect(10, 50, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.flowOutLbl.setFont(font)
        self.flowOutLbl.setText("")
        self.flowOutLbl.setObjectName("flowOutLbl")
        self.valveEdit = QtWidgets.QLineEdit(Dialog)
        self.valveEdit.setGeometry(QtCore.QRect(10, 240, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.valveEdit.setFont(font)
        self.valveEdit.setMaxLength(4)
        self.valveEdit.setFrame(True)
        self.valveEdit.setObjectName("valveEdit")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(20, 320, 301, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 360, 59, 14))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 410, 59, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Port = QtWidgets.QComboBox(Dialog)
        self.Port.setGeometry(QtCore.QRect(100, 352, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Port.setFont(font)
        self.Port.setObjectName("Port")
        self.Speed = QtWidgets.QComboBox(Dialog)
        self.Speed.setGeometry(QtCore.QRect(100, 400, 131, 31))
        self.Speed.setObjectName("Speed")
        self.ConnectButton = QtWidgets.QPushButton(Dialog)
        self.ConnectButton.setGeometry(QtCore.QRect(260, 390, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ConnectButton.setFont(font)
        self.ConnectButton.setObjectName("ConnectButton")
        self.label1_2 = QtWidgets.QLabel(Dialog)
        self.label1_2.setGeometry(QtCore.QRect(10, 110, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label1_2.setFont(font)
        self.label1_2.setObjectName("label1_2")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(151, 127, 121, 151))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.radioManual = QtWidgets.QRadioButton(self.groupBox)
        self.radioManual.setGeometry(QtCore.QRect(10, 120, 102, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioManual.setFont(font)
        self.radioManual.setChecked(True)
        self.radioManual.setAutoExclusive(True)
        self.radioManual.setObjectName("radioManual")
        self.radioAuto = QtWidgets.QRadioButton(self.groupBox)
        self.radioAuto.setGeometry(QtCore.QRect(10, 40, 102, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioAuto.setFont(font)
        self.radioAuto.setObjectName("radioAuto")
        self.targetflowEdit = QtWidgets.QLineEdit(Dialog)
        self.targetflowEdit.setGeometry(QtCore.QRect(10, 150, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.targetflowEdit.setFont(font)
        self.targetflowEdit.setMaxLength(4)
        self.targetflowEdit.setFrame(True)
        self.targetflowEdit.setObjectName("targetflowEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(172, 5, 191, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.fmUnits = QtWidgets.QComboBox(self.groupBox_2)
        self.fmUnits.setGeometry(QtCore.QRect(102, 30, 81, 23))
        self.fmUnits.setObjectName("fmUnits")
        self.valveUnits = QtWidgets.QComboBox(self.groupBox_2)
        self.valveUnits.setGeometry(QtCore.QRect(102, 65, 81, 23))
        self.valveUnits.setObjectName("valveUnits")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(7, 32, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 66, 91, 16))
        self.label_5.setObjectName("label_5")
        self.groupBox.raise_()
        self.label1.raise_()
        self.label.raise_()
        self.flowOutLbl.raise_()
        self.valveEdit.raise_()
        self.line.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.Port.raise_()
        self.Speed.raise_()
        self.ConnectButton.raise_()
        self.label1_2.raise_()
        self.targetflowEdit.raise_()
        self.groupBox_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label1.setText(_translate("Dialog", "real flow"))
        self.label.setText(_translate("Dialog", "valve input"))
        self.valveEdit.setInputMask(_translate("Dialog", "0000"))
        self.label_2.setText(_translate("Dialog", "Port"))
        self.label_3.setText(_translate("Dialog", "Speed"))
        self.ConnectButton.setText(_translate("Dialog", "Connect"))
        self.label1_2.setText(_translate("Dialog", "target flow"))
        self.groupBox.setTitle(_translate("Dialog", "control"))
        self.radioManual.setText(_translate("Dialog", "Manual"))
        self.radioAuto.setText(_translate("Dialog", "Auto"))
        self.targetflowEdit.setInputMask(_translate("Dialog", "0000"))
        self.groupBox_2.setTitle(_translate("Dialog", "units"))
        self.label_4.setText(_translate("Dialog", "flowmeter"))
        self.label_5.setText(_translate("Dialog", "valve"))

